### ISSUE TITLE
seba-in-a-box makefile issue

### ISSUE THREAD

**Issue by mike03052000** [opencord/automation-tools#1]
We try to install SEBA-in-a-Box but looks like make file was not working.

~/cord/automation-tools/seba-in-a-box$ make
make: Nothing to be done for 'ponsim'.

**Comment by zdw** [comment]
Could you add this to the SEBA bugtracker here? 

https://jira.opencord.org/projects/SEBA/issues

To log in, you'd need to make an account here: https://opencord.org/registration/

**Comment by mike03052000** [comment]
We logged an issue.
Thank you.
